version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
  "obs-browser-Update-to-C-20.patch",
  "obs-browser-enable-support-for-CEF-6613+.patch",
]
SPDX-FileCopyrightText = "obs-studio contributors"
SPDX-License-Identifier = "GPL-2.0-only"
